### ISSUE TITLE
setInterval needed for historical data

### ISSUE THREAD

**Issue by sams-code** [dalenguyen/stockai#1]
is there a way to setInterval  = 1min
This is how I use it
>>prices_list = td.get_historical_prices(start_date, end_date)
and right now the default is 1 day

**Comment by dalenguyen** [comment]
Hi @sams-code, this function will get historical prices. It doesn't change the result if it runs again. Are you sure that this is the right function that you wanna ask?

**Comment by sams-code** [comment]
Hi, I want historical data with data for every 5 minutes so I can see how the stock trended during those days

Thanks


________________________________

**Comment by dalenguyen** [comment]
You can try this example code:

```
# sample set_interval code
import threading
  
def set_interval(func, sec):
    def func_wrapper():
        set_interval(func, sec)
        func()
    t = threading.Timer(sec, func_wrapper)
    t.start()
    return t

def sayHello():
     print("Hello!")

set_interval(sayHello, 1) # 1 second
```

if you want to run every 5 minutes, you have to replace number 1 by 5*60 = 300.

**Comment by dalenguyen** [comment]
Closed due to inactivity.
